version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    restart: always
    volumes: 
      - ./sql/config:/etc/mysql/mysql.conf.d/
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: spark
      MYSQL_USER: spark
      MYSQL_PASSWORD: spark
      MYSQL_ROOT_PASSWORD: spark


  app:
    build: .
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - .:/home/spark/spark-web-app
    depends_on:
      - db
    links:
      - db
    environment:
      NODE_ENV: dockerdev
      PORT: 3000
      DB_HOST: db
      DB_USER: spark
      DB_PASSWORD: spark
      DB_DATABASE: spark
