version: '2'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - .:/home/spark/spark-web-app
    environment:
      NODE_ENV: development
      PORT: 3000
